arguments:
    data_fetch_params:
      url_api: 'https://jsonplaceholder.typicode.com/posts'
    schema_style:
      type: 'object'
      properties:
        userId:
          type: 'number'
        id:
          type: 'number'
        title:
          type: 'string'
        body:
          type: 'string'
      required:
        - 'userId'
        - 'id'
        - 'title'
        - 'body'
    outputs:
      output_dir: 'output'
      raw_api_data_path: 'output/api_data.json'
      clean_data_path: 'output/cleaned_data.json'
      loading_df_path: 'output/loading_data_df.csv'
    db_arguments:
      host : 'localhost' 
      port: '3306'
      user: 'user'
      password: 'password'
      database: 'api_data'
      table: 'posts'
